# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44701fb041641ffe8b06344983d772aed9f7633ed87cda82114471d68e5c516a2b55d053c6ff87e321120a386ec47b132c5dd5564cf3cb76c71a6743b8aeb872

test:
  secret_key_base: 75a5c7f09737e5acd8d96be0888f505b369e981e90f41203c473dc08c8db097fd8b9fec9380bb98c3b6657aedd55d0b6c5133de2fe4971ca1f31f95d659d81bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
